In [15]:
import pandas as pd
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\asus\miniconda3\lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\asus\miniconda3\lib\site-packages (from scikit-learn) (2.0.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\asus\miniconda3\lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in c:\users\asus\miniconda3\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\asus\miniconda3\lib\site-packages (from scikit-learn) (3.6.0)

In [63]:
house_price_data=pd.read_csv("HousePricePrediction.csv")
print(house_price_data.isnull().values.any())
house_price_data.isnull().sum()

house_price_data.fillna(house_price_data.mean(numeric_only=True), inplace=True)

True

In [64]:
house_price_data.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [66]:
X=house_price_data.drop(columns=["MSZoning","LotConfig","BldgType","Exterior1st","SalePrice"])
y=house_price_data["SalePrice"]

In [67]:
X.head()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
0,0,60,8450,5,2003,2003,0.0,856.0
1,1,20,9600,8,1976,1976,0.0,1262.0
2,2,60,11250,5,2001,2002,0.0,920.0
3,3,70,9550,5,1915,1970,0.0,756.0
4,4,60,14260,5,2000,2000,0.0,1145.0

In [68]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [69]:
X_test.head()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF
2437,2437,85,6760,5,1962,1962,0.0,896.0
2470,2470,60,9780,9,1950,2005,398.0,976.0
2359,2359,20,6285,5,1977,1977,351.0,894.0
789,789,60,12205,8,1966,2007,0.0,832.0
1642,1642,60,7500,5,2000,2001,0.0,1058.0

In [70]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [71]:
y_pred=model.predict(X_test)
y_pred

array([159809.60947988, 187420.35867438, 164494.67121565, 189606.76152801,
       192216.89982699, 219665.0293801 , 140362.64735036, 207321.91727942,
       126764.54238915, 198905.46762065, 180390.18756528, 196127.89996772,
       167212.3259072 , 197422.75118111, 182041.08033732, 186470.89763647,
       161979.75412609, 189689.35787865, 131713.86678133, 162524.60609725,
       195972.1829348 , 133251.99325483, 134767.31014369, 197085.2289969 ,
       209703.02673835, 190915.27949594, 183290.62136697, 153153.42796892,
       201818.34344899, 162704.97192112, 226431.69514414, 159821.06985428,
       194358.88439   , 192300.82231762, 205334.30851593, 210401.37815916,
       175329.12497006, 168057.77911764, 158159.1959901 , 169953.7049056 ,
       136839.11022038, 190340.96385917, 221054.11659533, 176247.27894606,
       168728.77168785, 176424.50629392, 203945.52829484, 184274.70397196,
       175161.61632376, 240434.7176764 , 154449.08626044, 182768.94401745,
       141565.75484014, 205584.93021998, 167051.87015895, 132991.98269255,
       159928.05329094, 178197.49933709, 218623.48270115, 170194.38284956,
       167690.12449228, 152506.71479649, 174620.19771416, 164696.64284167,
       170368.04404451, 203756.89491564, 203256.99962941, 160953.39418155,
       167760.38454832, 166429.69174163, 192840.94474159, 162776.40739701,
       187500.45732126, 219439.94151021, 139689.99211975, 118222.16465114,
       197865.98408081, 139344.46453208, 202893.35730019, 188254.95767673,
       164992.62082306, 198175.06441204, 190702.71162019, 151461.27318729,
       167230.71578297, 186072.26577479, 122851.57022257, 162033.10371377,
       141293.01090497, 174842.38743995, 174563.31356717, 139307.19257304,
       153695.16055768, 228022.31590346, 181292.68780367, 167524.82948722,
       165277.79821327, 200471.78096083, 155723.49281847, 178764.97925753,
       165587.81722405, 177200.68042034, 170382.61859379, 198284.83193283,
       193762.0056492 , 167809.84466595, 143909.90630561, 173279.12961017,
       223356.95890483, 182757.06176576, 185334.31522716, 154165.14303927,
       203540.67997863, 247558.65006674, 211013.61249139, 165623.37739701,
       157798.30941873, 206706.76067638, 245471.77841154, 208391.32727179,
       155272.31805918, 174515.31228115, 203873.84760291, 156832.01810658,
       152639.76058205, 156866.12021338, 174176.31773169, 189005.35451548,
       195898.39117891, 212084.49846125, 174365.90251148, 144251.74280565,
       199703.32088341, 175389.21671434, 167277.67795167, 170893.47993715,
       203712.83342061, 199560.11877683, 225367.0337701 , 201959.77866343,
       162091.54729483, 172399.06179563, 148785.06033977, 193193.61753619,
       221682.83408152, 218342.24984365, 173694.54066239, 238403.2403112 ,
       191703.63188994, 196090.73098367, 171859.87015716, 221198.85361491,
       136446.71103178, 168439.21710052, 133948.96935034, 137471.2334129 ,
       204054.31287349, 210783.09465705, 154758.40578059, 130651.59085353,
       226908.10894061, 229947.9589058 , 208665.53838168, 169597.29299371,
       150358.10699058, 163386.3037537 , 226900.65603033, 195887.47491692,
       174302.79883468, 128739.14956716, 150723.65452906, 156020.18820476,
       192097.66978647, 199124.56916496, 199225.70549578, 212307.8437088 ,
       172026.71385768, 185103.28942836, 168232.84240383, 200819.57272609,
       214867.37691726, 206143.86339649, 172602.84366663, 196936.20304385,
       194435.75798126, 198325.5235209 , 210782.42593943, 219970.36076555,
       182203.76083979, 166839.88219727, 205138.86380883, 211679.49703506,
       134432.31488249, 154140.04515062, 191356.89836841, 219615.35626076,
       219104.04161   , 184537.4440014 , 252098.89458917, 182963.45719813,
       169330.49030602, 180097.9873863 , 170199.24980662, 160211.82567683,
       174600.05051143, 106027.94102985, 144916.19058648, 182274.81141431,
       146148.26531332, 175305.34838735, 137267.07549292, 172865.87718437,
       211954.59047443, 192816.63871497, 198525.79167402, 136448.48677783,
       198299.66545796, 137027.63109709, 185770.64591007, 183016.10214354,
       131778.72847605, 171251.08104561, 204065.93392317, 116158.88010907,
       219352.31135274, 178697.77418587, 197222.55174471, 199284.45690306,
       148803.63686285, 131381.50814148, 142961.03053972, 160387.20580975,
       155762.66433535, 188543.1210367 , 158496.70745675, 176120.08701106,
       162208.23246437, 185341.60330661, 147500.13837474, 147322.02942108,
       219221.43039897, 164645.0787924 , 218512.61087654, 219334.83075507,
       235316.21634773, 172974.84551495, 168598.08116899, 197496.16542021,
       191235.09950172, 181470.15124514, 201712.97376507, 164178.26416025,
       173788.31601906, 138361.23183909, 229065.14403015, 135292.06222029,
       146408.87835974, 163984.91484213, 211554.7413384 , 190245.23672297,
       155867.09265609, 178833.11393941, 154699.34947354, 218031.80631816,
       221285.59679008, 198505.43648759, 179453.1975829 , 175228.89478271,
       218398.07530465, 189956.4598686 , 176772.70307808, 149921.65033067,
       178775.33703642, 135707.38650486, 211215.5543174 , 191836.36158658,
       165115.03961572, 220715.31659873, 178103.32271216, 181619.25977142,
       221655.41178684, 182513.00249114, 166094.89043627, 145111.07130849,
       224978.89704272, 167016.63337551, 198679.92907438, 163737.47074387,
       161970.31240181, 149792.18382932, 175411.01306559, 195272.89871111,
       176722.67681374, 197030.09975919, 181311.80301768, 197457.60961817,
       236454.89275877, 150208.21920094, 171828.51961777, 179082.92602397,
       185540.10964722, 212098.76922464, 179923.35624804, 212889.47979442,
       153902.34215911, 232177.67883485, 188439.554966  , 215947.69219831,
       164659.44814849, 188246.10760721, 186408.38606062, 166300.28171665,
       181975.42046286, 185867.8341436 , 160684.25591975, 176818.75572831,
       141219.05346718, 166724.11888963, 208668.20816023, 162252.39177188,
       179016.10496765, 197818.80376052, 212257.23711334, 118757.58626192,
       184092.05413434, 211160.43796056, 187477.16422692, 178490.99829088,
       115460.12525601, 171514.05966269, 148291.43980559, 200216.59721921,
       128607.05796434, 120301.05563367, 211560.50905532, 159170.68668876,
       219305.7033665 , 186589.67484996, 176919.14385303, 175696.9887639 ,
       147594.13676186, 167527.03223403, 168015.38591074, 178111.89800974,
       186361.85450854, 171749.80521583, 202719.84074821, 140424.05588521,
       180364.41573937, 126079.54575935, 174010.53292704, 199833.51570941,
       163303.68239385, 204072.70598966, 200691.69363593, 178611.66487198,
       139320.91124862, 188544.69684354, 148279.33801854, 225334.6025655 ,
       132336.22091385, 192136.15291672, 174958.93163858, 196759.41876628,
       193845.87998635, 178359.44706434, 202770.91532669, 197925.10626321,
       192508.5919072 , 182546.70416396, 165824.28331263, 152383.97176357,
       166924.99056047, 139330.22131522, 180998.01564222, 190036.0461763 ,
       179848.22098588, 176787.58723208, 189670.75530796, 167580.87136366,
       170704.4696721 , 238845.14610183, 191986.21960859, 177427.93953567,
       138142.12489121, 201283.22450365, 194766.37773573, 165153.66956822,
       160204.25757372, 169135.61243623, 161050.47327955, 206518.25677241,
       199105.97519535, 187883.09043594, 188500.60748379, 155445.17259008,
       194249.12773906, 222251.89150892, 162053.10244264, 177824.05950301,
       169199.24583992, 111884.41343721, 184393.79696439, 176279.22205115,
       158864.5282985 , 214007.24266339, 148711.24512546, 192069.37073054,
       188199.03486489, 146625.24895764, 137473.92894175, 171834.81088579,
       171146.17066802, 204153.5093042 , 142338.01153429, 181521.11780341,
       182833.53517751, 185557.7309659 , 219337.49825376, 227749.47899418,
       194522.75735508, 158635.52666481, 157525.64195514, 195735.62735479,
       186518.10872405, 202201.67485156, 209003.68749186, 226923.80343392,
       182242.29359503, 190193.31910102, 177598.10475379, 148203.51330007,
       166568.99937155, 203229.50026829, 175860.59121233, 171139.3178456 ,
       133501.3834534 , 202408.80392766, 158861.75316881, 137068.83854605,
       187515.61336287, 149357.12668306, 162660.67662672, 225903.17969295,
       180171.97755486, 152636.31384394, 139651.68314452, 204651.59914622,
       183869.94691428, 157861.43695765, 217621.10665374, 161020.20126186,
       184308.30761566, 188633.3310244 , 178327.58764407, 153187.88626541,
       158360.87565906, 160617.52649809, 177935.25577573, 138101.19175233,
       162522.12907688, 191390.23379474, 164954.49694831, 234517.9638385 ,
       208059.23565383, 146752.41827092, 174874.41710099, 266187.79734823,
       192715.81927938, 155927.15651935, 246533.43801011, 155856.6758382 ,
       194728.20987309, 205692.10567377, 198805.70188327, 195723.8522999 ,
       171544.29316887, 224425.53588641, 189449.58286627, 144651.39976922,
       224841.51462195, 194210.63229859, 154543.88695078, 217689.42481367,
       166687.30643047, 154094.74762489, 174231.19769355, 160554.82554165,
       154359.40529443, 197256.01235541, 212003.54808773, 193856.24772213,
       209810.69515246, 198923.0408728 , 437101.71186338, 218546.93520421,
       191202.9326197 , 209898.83766058, 138646.80655523, 179418.68915084,
       145352.56344739, 207957.85944522, 193950.0053353 , 225334.21062525,
       134079.8366727 , 192445.14177543, 142161.65550454, 197475.53580253,
       144664.7074444 , 151798.4635798 , 202825.35586901, 200811.26590093,
       184035.95608208, 180487.32078675, 207307.03565198, 194103.28150977,
       178616.94122912, 214149.38338886, 170169.42093525, 205196.56885978,
       143331.84871377, 173860.43142224, 182169.16226911, 196404.29016806,
       157179.97415961, 155483.6103686 , 221954.99941304, 187982.67422412,
       191789.12214752, 165446.75868472, 138232.97108172, 170450.16056356,
       255064.5188683 , 188641.46328872, 199841.12293577, 164749.81285251,
       142223.92628784, 164681.8168093 , 213815.56653142, 200873.54450798,
       175141.79134624, 179845.99993776, 181682.2197504 , 182140.88624868,
       167616.21649126, 144653.05343775, 182198.71305863, 153609.8279271 ,
       144080.77120348, 234806.23406476, 204483.19373414, 201584.60527439,
       153663.1824198 , 179709.00238501, 230906.11503933, 125947.84081303,
       175289.11628249, 190096.9582177 , 163939.67220786, 177952.40270991,
       205705.41844681, 189468.27733544, 168036.51425658, 169905.88123481,
       162518.31593986, 186101.30973434, 125613.3482526 , 154763.79201102,
       170668.16786295, 119236.66648492, 201263.95893663, 203398.38827376,
       150472.03790214, 180359.82674346, 190894.26961189, 168369.85947807,
       173879.64732464, 194224.57902287, 203428.90480332, 157077.23736126,
       227553.44734724, 236149.47322161, 116695.59753619, 200050.75979113])

In [72]:
y_test

2437    180921.19589
2470    180921.19589
2359    180921.19589
789     187500.00000
1642    180921.19589
            ...
2880    180921.19589
2295    180921.19589
2222    180921.19589
1090     92900.00000
542     213250.00000
Name: SalePrice, Length: 584, dtype: float64

In [74]:
from sklearn.metrics import r2_score
r2=r2_score(y_test, y_pred)
print("r-squared: ",r2)

n=X_test.shape[0]
p=X_test.shape[1]

adjusted_r2=1-((1-r2)*(n-1)/(n-p-1))
print("adjusted r^2:",adjusted_r2)

r-squared:  0.31819611361834754
adjusted r^2: 0.3087101465034724